.PHONY: clean All

All:
	@echo "----------Building project:[ ModifiedProgram - Debug ]----------"
	@cd "/Users/iseung-won/personal_study/C++/section5/ModifiedProgram" && "$(MAKE)" -f  "ModifiedProgram.mk"
clean:
	@echo "----------Cleaning project:[ ModifiedProgram - Debug ]----------"
	@cd "/Users/iseung-won/personal_study/C++/section5/ModifiedProgram" && "$(MAKE)" -f  "ModifiedProgram.mk" clean
