.PHONY: clean All

All:
	@echo "----------Building project:[ firstProgram - Debug ]----------"
	@cd "firstProgram" && "$(MAKE)" -f  "firstProgram.mk"
clean:
	@echo "----------Cleaning project:[ firstProgram - Debug ]----------"
	@cd "firstProgram" && "$(MAKE)" -f  "firstProgram.mk" clean
